from rdflib import URIRef

RDF2GRAPHML_NS_BASE: str = "https://www.hedenus.de/rdf2graphml/"

RDF2GRAPHML_ICON = RDF2GRAPHML_NS_BASE + "icon"
RDF2GRAPHML_COLOR = URIRef(RDF2GRAPHML_NS_BASE + "color")
RDF2GRAPHML_SHAPE = URIRef(RDF2GRAPHML_NS_BASE + "shape")
RDF2GRAPHML_LINK = URIRef(RDF2GRAPHML_NS_BASE + "Link")
